# ==================== Nom de la CI ====================
name: Hands-digits training pipeline

# ==================== Déclencheurs ====================
on:
  push:
    branches:
      - main
    paths: 
      - 'train/**'
      - '.github/workflows/train_pipeline.yml'
  workflow_dispatch:

# ==================== Bloquage automatique ====================
concurrency:
  group: train-pipeline-${{ github.ref }}
  cancel-in-progress: true

# ==================== Jobs ====================
jobs:
  train-pipeline:
    runs-on: [self-hosted, gpu, cuda]

    permissions:
      contents: read

    defaults:
      run:
        shell: powershell

    env:
      PYTHONUNBUFFERED: "1"  
    
    # ==================== Steps ====================
    steps:

      # Cloning repository on virtual machine
      - name: checkout-repository
        uses: actions/checkout@v4
      
      # Update at your convenience if your runner does not run on Windows with :
        # echo "ULTRALYTICS_API_KEY=${{ secrets.ULTRALYTICS_API_KEY }}" > .env
      - name: env-file-setup
        run: |
          "ULTRALYTICS_API_KEY=${{ secrets.ULTRALYTICS_API_KEY }}" > .env
      
      # ==================== GESTION AUTOMATIQUE DU VENV ====================
      - name: training-venv-setup
        working-directory: train
        run: |
          python3 -m venv .venv_train
          ./.venv_train/Scripts/python.exe -m pip install --upgrade pip
          ./.venv_train/Scripts/python.exe -m pip install -r requirements.txt

      # ==================== ML Pipeline avec VENV local ====================
      - name: pipeline-run
        working-directory: train
        run: ./.venv_train/Scripts/python.exe pipeline.py

      - name: upload-artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: train-pipeline-artifacts
          if-no-files-found: warn
          path: |
            runs/**
            train/reports/**
